if &compatible
  set nocompatible
endif

set incsearch
set list
set wildmenu
set encoding=utf-8
set number

source ~/.vim/vimrc.dein
source ~/.vim/vimrc.colors
source ~/.vim/vimrc.indent
source ~/.vim/vimrc.completion
source ~/.vim/vimrc.snippet

filetype plugin indent on
